---
- hosts: all
  name: Add cis-92 packages
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - python3-pip 
          - python3-venv
          - apache2
          - php
          - php-xml
          - nodejs
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
    - name: Extract dokuwiki to /var/www/html
      ansible.builtin.unarchive:
        src: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /var/www/html
        remote_src: yes
    - name: Create an ext4 filesystem on /dev/disk/by-id/google-system
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-system
    - name: Create an ext4 filesystem on /dev/disk/by-id/google-data
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-data
    - name: Create directory /system
      file:
        path: /system
        state: directory
        mode: '0644'
    - name: Create directory /var/www/data
      file:
        path: /var/www/data
        state: directory
        mode: '0644'
    - name: Mount attached disk
      ansible.posix.mount:
          fstype: ext4
          path: /var/www/data
          src: /dev/disk/by-id/google-data
          state: present
    - name: Mount attached disk
      ansible.posix.mount:
          fstype: ext4
          path: /system
          src: /dev/disk/by-id/google-system
          state: present
    - name: copy backup script to /etc/cron.hourly/backup
      ansible.builtin.copy:
        src: /etc/foo.conf
        dest: /etc/cron.hourly/backup
    

